services:

  minio:
    image: minio/minio
    container_name: minio

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123

    volumes:
      - ./minio-data:/data

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter

    ports:
      - "8888:8888"

    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./scripts:/home/jovyan/scripts

    command: >
      bash -c "pip install --no-cache-dir minio &&
      start-notebook.py"

    depends_on:
      - minio

  spark-master:
    image: apache/spark:3.5.5
    container_name: spark-master
    hostname: spark-master

    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.master.Master"
      ]

    ports:
      - "7077:7077"
      - "8080:8080"

    volumes:
      - ./scripts:/opt/spark-apps
      - ./ivy-cache:/home/spark/.ivy2

    depends_on:
      - minio

  spark-worker:
    image: apache/spark:3.5.5
    container_name: spark-worker
    hostname: spark-worker

    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "--cores",
        "2",
        "--memory",
        "2g",
        "spark://spark-master:7077"
      ]

    ports:
      - "8081:8081"

    volumes:
      - ./ivy-cache:/home/spark/.ivy2

    depends_on:
      - spark-master